accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

cart/urls.py
from django.urls import path
from .import views


app_name = 'cart'

urlpatterns = [
  #path('', views.get_cart, name='get_cart'),
  path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
  path('remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
  path('subscribe/', views.subscribe, name='subscribe'),
  #path('remove_cart/', views.remove_cart, name='remove_cart'),
  #
]   

home/urls.py
from django.urls import path
from home import *
from home import views

app_name = 'home'

urlpatterns = [
    path("", views.home, name="home"),
    path('products/<str:category>', views.products, name="products"),
    path('cart', views.cart, name="cart"),
    path('checkout', views.checkout, name="checkout"),
    path("placeorder", views.coredirect, name="placeorder"),
]

small_basket/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("home.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('cart/', include("cart.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart')
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    def __str__(self):
        return f"Cart of ${self.user.username}"

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_items')

    def __str__(self):
        return self.product.name

home/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    p_id = models.CharField(max_length=10, primary_key=True)
    p_name = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.IntegerField(default=0)
    image = models.URLField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def is_out_of_stock(self):
        return (self.stock>0)

    def __str__(self):
        return self.p_name

cart/views.py
from django.http.response import HttpResponse
from django.http import HttpResponseRedirect  
from django.shortcuts import redirect, render
from home.models import Product
from .models import CartItem, Cart

def add_to_cart(request):
    id = request.POST.get('id')
    item = Product.objects.get(p_id=id)

    if request.user.is_authenticated: #user logged in
        try:
            cart = Cart.objects.get(user=request.user) #user cart exists
        except:
            cart = Cart.objects.create(user = request.user) #user cart doesnt exist and is hence created
        product = CartItem.objects.filter(product=item, cart=cart) #looks for item in the cart
        if item.stock>=1:
            if product: #product already present in cart
                product = product[0]
                product.quantity += 1
                product.price += item.price
                cart.total += item.price
                product.save()
                item.stock -= 1
                item.save()
                cart.save()

            else: #product not in cart
                new_item = CartItem(product=item, price=item.price, quantity=1, cart=cart)
                cart.total += new_item.price
                new_item.save()
                item.stock -= 1
                item.save()
                cart.save()
            response = HttpResponse(status=201)
        else:
            pass
    return response


def remove_from_cart(request):
    id = request.POST.get('id')
    item = Product.objects.get(p_id=id)

    cart = Cart.objects.get(user=request.user)
    product = CartItem.objects.filter(product=item, cart=cart)
    product = product[0]
    if product.quantity>0:
        product.quantity -= 1
        product.price -= item.price
        item.stock += 1
        cart.total -= item.price
    else:
        product.delete()
    product.save()
    item.save()
    cart.save()

    cartitem = CartItem.objects.all()
    cart = Cart.objects.get(user = request.user)
    return render(request,'home/cart.html', {'cartitem': cartitem, 'cart':cart})


def subscribe(request):
    id = request.POST.get('id')
    item = Product.objects.get(p_id=id)

    if request.user.is_authenticated: #user logged in
        try:
            cart = Cart.objects.get(user=request.user) #user cart exists
        except:
            cart = Cart.objects.create(user = request.user) #user cart doesnt exist and is hence created
        product = CartItem.objects.filter(product=item, cart=cart) #looks for item in the cart
        if item.stock>=7:
            if product: #product already present in cart
                product = product[0]
                product.quantity += 7
                product.price += 6*item.price
                cart.total += 6*item.price
                product.save()
                item.stock -= 7
                item.save()
                cart.save()

            else: #product not in cart
                new_item = CartItem(product=item, price=6*item.price, quantity=7, cart=cart)
                cart.total += new_item.price
                new_item.save()
                item.stock -= 7
                item.save()
                cart.save()
            response = HttpResponse(status=201)
        else:
            pass
    return response

home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from home.models import Category, Product
from cart.models import Cart, CartItem
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.db import connection

def home(request):
    category_ids= Category.objects.all()
    return render(request,'home/homepage.html', {'categories':category_ids} )

def products(request, category):
    products= Product.objects.all()
    
    try:
        cart = Cart.objects.get(user = request.user)
        cartitems = CartItem.objects.filter(cart = cart)
    except:
        cartitems = None
    return render(request,'home/products.html', {'products':products, 'selected_category':category, 'items' : cartitems})    

def cart(request):
    cartitem = CartItem.objects.all()
    cart = Cart.objects.get(user = request.user)
    length = len(CartItem.objects.filter(cart=cart).exclude(quantity=0)) > 0
    return render(request,'home/cart.html', {'cartitem': cartitem, 'cart':cart, 'list' : length})

def checkout(request):
    cart = Cart.objects.get(user = request.user)
    return render(request, 'home/checkout.html', {'cart': cart})

def coredirect(request):
    cart = Cart.objects.get(user = request.user)
    with connection.cursor() as cursor:
        cursor.execute("DELETE from cart_cartitem where cart_id = %s ", [cart.id])
    cart.total = 0
    cart.save()

    return redirect("/")

home/templates/home/base.html
{%load static%}
<!DOCTYPE html>
<html>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <head>
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
        <title>Small Basket</title>
        <link rel="stylesheet" href="{% static 'home/grid.css' %}">
        <link rel="stylesheet" href="{% static 'home/base.css' %}"> 
        <link rel="stylesheet" href="{% static 'home/normalize.css' %}">
        {%block css%}{%endblock%}
    </head>
    
    <body>
        <div class="topnav">
            <a id="topnav-left" href="{% url 'home:home' %}"><img src="{% static 'home/img/logo.png' %}"></a>
            {% block nav_menu %}
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <a class="topnav-bt" href="#">Hi, {{ user.username|safe }} </i></a>
                    <div class="dropdown-content">
                        <a href="#" onClick="document.getElementById('logoutform').submit()"> Logout </a>
                        <a href="{% url 'home:cart' %}">My Cart</a>
                        <form id = "logoutform" action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>
                    </div>
                </div>
                
            {% else %}
                <a class="topnav-bt" id="sign-in" href="/accounts/login">Sign In</a>
            {% endif %}
            {%endblock%}
        </div>
        {%block body%}{%endblock%}
        <script type="text/javascript" src="{% static 'home/script/cart.js' %}"></script> 
    </body>
</html>

home/templates/home/cart.html
{%extends "home/base.html"%}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/cart.css' %}">
    <link rel="stylesheet" href="{% static 'home/products.css' %}">
{% endblock css %}
{%block body%}
<h1>My Cart</h1>
{% if list %}
{% for item in cartitem %}
    {% if item.cart.id == cart.id and item.quantity > 0 %}
        <div class="product row">
            <div class="col span_1_of_5 product-img">
                <img src={{item.product.image}}>
            </div>
            <div class="col span_3_of_5 product-info">
                <h1>{{item.product.p_name}}</h1>  
                    <br>
                  <p>Qty: {{ item.quantity }} </p>
                  
            </div>  
            <div class="col span_1_of_5 ">
                    <h1>₹{{item.price }}</h1>
                    <br>
                  <div>
                    <button data-id="{{ item.product.p_id }}" class="delete_btn">Delete</button>
                  </div>
            
            </div>
        </div>

        {% endif %}
        {% endfor %}
    
<div class="sub_total">
    <h1>Total(): ₹{{ cart.total }}</h1>
  </div>
  <div class="checkout_btn_div" >
        <form action="{% url 'home:checkout'%}" method="GET">
        <button type="submit" class="checkout_btn">Checkout</button>
        </form>
  </div>
</div>


{% else %}
<img class="center" src="https://cdn-icons-png.flaticon.com/512/102/102661.png"></img>  
<br>
<p class="yeet">
    Your cart is empty! Click <a id="default" href="{% url  'home:home' %}"> here </a> to continue shopping. 
</p>
{%endif%}

{%endblock body%}

home/templates/home/checkout.html
{%extends "home/homepage.html"%}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/signup.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
{% endblock css %}

{%block nav_menu%}{%endblock%}
{%block body%}
<div id="cover">
        <div class="overlay"></div>
        <div class="welcome">
            <h1>Checkout</h1>
            <form action="{% url 'home:placeorder' %}" method="get">
    
                <h3> Your Total is: </h3>
                <h2> {{cart.total}}</h2>
                <div class = "prompter">
                Please Note that only Cash-on-delivery Payment Option is available
                </div>
                <br>
                <div id="submitbtn" class="text-center">
                    <button class="btn btn-secondary mx-auto" type="submit">Place Order</button>
                </div>
            </form>

            <div class = "prompter">
                Unsure about purchase? Click <a href="{% url 'home:home' %}">here </a> to go back.
            </div>
        </div>    
    </div>

{%endblock body%}

home/templates/home/homepage.html
{%extends "home/base.html"%}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/homepage.css' %}">
{% endblock css %}
{%block body%}
    <div id="cover">
        <div class="overlay"></div>
        <div class="welcome">
            <h1>Welcome to Small Basket</h1>
            <p>Delivering all your grocery needs with utmost care</p>
        </div>
        <table class="services">
            <tr>
                <td>
                    <img src="{% static 'home/img/delivery.png'%}">
                </td>
                <td>
                    <img src="{% static 'home/img/savings.png'%}">
                </td>
                <td>
                    <img src="{% static 'home/img/cod.png'%}">
                </td>
                <td>
                    <img src="{% static 'home/img/subscribe.png'%}">
                </td>
            </tr>
            <tr>
                <td>
                    <h3>Free One Day Delivery</h3>
                    <p>Order and get your groceries delivered by the next day</p>
                </td>
                <td>
                    <h3>20% Discount</h3>
                    <p>Avail a discount of upto 20% on your first order delivery</p>
                </td>
                <td>
                    <h3>COD</h3>
                    <p>Cash-On-Delivery Payment mode available</p>
                </td>
                <td>
                    <h3>Small Basket Subscription</h3>
                    <p>Save more and get scheduled deliveries with our Small Basket Subscription</p>
                </td>
            </tr>
        </table>
    </div>
    <div class="categories">
        <h1>Shop By Category</h1>
         <!-- {%for category in categories%}
        <p>{{category}}</p>
        {%endfor%}  -->
        <table>
            <tr>
                <td>
                    <a href="{%url 'home:products' category="Fruits" %}">
                        <img src="{% static 'home/img/fruits.png' %}"/>
                        <p>Fruits</p>
                    </a>
                </td>
                <td>
                    <a href="{%url 'home:products' category="Vegetables" %}">
                        <img src="{% static 'home/img/vegetable.png' %}"/>
                        <p>Vegetables</p>
                    </a>
                </td>
                <td>
                    <a href="{%url 'home:products' category="Dairy" %}">
                        <img src="{% static 'home/img/dairy.png' %}"/>
                        <p>Dairy</p>
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="{%url 'home:products' category="Meats and Seafood" %}">
                        <img src="{% static 'home/img/barbecue.png' %}"/>
                        <p>Meats and Seafood</p>
                    </a>
                </td>
                <td>
                    <a href="{%url 'home:products' category="Grains and Staples" %}">
                        <img src="{% static 'home/img/wheat-sack.png' %}"/>
                        <p>Grains and Staples</p>
                    </a>
                </td>
                <td>
                    <a href="{%url 'home:products' category="Luxury Items" %}">
                        <img src="{% static 'home/img/platter.png' %}"/>
                        <p>Luxury Items</p>
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="{%url 'home:products' category="Baked Goods" %}">
                        <img src="{% static 'home/img/bread.png' %}"/>
                        <p>Baked Goods</p>
                    </a>
                </td>
                <td>
                    <a href="{%url 'home:products' category="Snacks and Beverages" %}">
                        <img src="{% static 'home/img/snack.png' %}"/>
                        <p>Snacks and Beverages</p>
                    </a>
                </td>
                <td>
                    <a href="{%url 'home:products' category="Frozen Foods" %}">
                        <img src="{% static 'home/img/frozen-food.png' %}"/>
                        <p>Frozen Foods</p>
                    </a>
                </td>
            </tr>
        </table>
    </div>     
{%endblock body%}

home/templates/home/products.html
{%extends "home/base.html"%}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'home/products.css' %}">
{% endblock css %}
{%block body%}
    
    <h1>{{selected_category}}</h1>
    {%for product in products%}
        {%if product.category.name == selected_category %} 
            <div class="product row">
                <div class="col span_1_of_5 product-img">
                    <img src={{product.image}}>
                </div>
                <div class="col span_3_of_5 product-info">
                    <h1>{{product.p_name}}</h1>
                    <br>
                    <button method="POST" onclick="showcart('{{ product.p_id }}')" data-id="{{ product.p_id }}" action="{% url 'cart:subscribe' %}" class="sub_btn" type="submit">
                        Subscribe
                    </button>
                    <br>
                    <br>
                        <label >Weekly Subscription- Save upto 10%</label><br>
                        <label>Pre-place an order for delivery for an entire week and get an immediate discount of upto 10%</label><br>

                </div>
                <div class="col span_1_of_5 add-to-cart">
                    <h1>₹{{product.price}}</h1>
                    
                    <div class="buttons">
                        <img src="{% static 'home/img/cart.png'%}">
                        {% if product.stock > 0 %}
                        <button method="POST" onclick="showcart('{{ product.p_id }}')" data-id="{{ product.p_id }}" action="{% url 'cart:add_to_cart' %}" class="add_to_cart_btn" type="submit">
                          Add to Cart
                        </button><br>
                        
                        {% else %}
                        <button disabled data-id="{{ product.p_id }}" class="add_to_cart_btn">
                          Add to Cart
                        </button>
                        
                        {% endif %}
                        <div class="inCart hidden" id="{{product.p_id}}">
                            {%for item in items%}
                                {% if item.product.p_id == product.p_id %}
                                    <br>
                                    <p >In Cart : {{ item.quantity}} </p>
                                {% endif %} 
                            {%endfor%}

                        </div>
                    </div>

                </div>
            </div>
        <!--<p>{{product.p_name}}</p>-->
        {%endif%} 
    {% endfor %}
    
{%endblock body%}